import React from 'react';



export const DataOrder = [
    {code: 'Proximitat', name: 'Proximitat'},
    {code: 'Edat', name: 'Edat'},
];

export const DataComarques = [
    {code: 'Alt Camp', name: 'Alt Camp'},
    {code: 'Alt Empordà', name: 'Alt Empordà'},
    {code: 'Alt Penedès', name: 'Alt Penedès'},
    {code: 'Alt Urgell', name: 'Alt Urgell'},
    {code: 'Alta Cerdanya', name: 'Alta Cerdanya'},
    {code: 'Alta Ribagorça', name: 'Alta Ribagorça'},
    {code: 'Andorra', name: 'Andorra'},
    {code: 'Anoia', name: 'Anoia'},
    {code: 'Bages', name: 'Bages'},
    {code: 'Baix Camp', name: 'Baix Camp'},
    {code: 'Baix Ebre', name: 'Baix Ebre'},
    {code: 'Baix Empordà', name: 'Baix Empordà'},
    {code: 'Baix Llobregat', name: 'Baix Llobregat'},
    {code: 'Baix Penedès', name: 'Baix Penedès'},
    {code: 'Baixa Cerdanya', name: 'Baixa Cerdanya'},
    {code: 'Barcelonès', name: 'Barcelonès'},
    {code: 'Berguedà', name: 'Berguedà'},
    {code: 'Capcir', name: 'Capcir'},
    {code: 'Conca de Barberà', name: 'Conca de Barberà'},
    {code: 'Conflent', name: 'Conflent'},
    {code: 'Fenolleda', name: 'Fenolleda'},
    {code: 'Garraf', name: 'Garraf'},
    {code: 'Garrigues', name: 'Garrigues'},
    {code: 'Garrotxa', name: 'Garrotxa'},
    {code: 'Gironès', name: 'Gironès'},
    {code: 'Illes Balears', name: 'Illes Balears'},
    {code: 'Maresme', name: 'Maresme'},
    {code: 'Montsià', name: 'Montsià'},
    {code: 'Noguera', name: 'Noguera'},
    {code: 'Osona', name: 'Osona'},
    {code: 'País Valencià', name: 'País Valencià'},
    {code: 'Pallars Jussà', name: 'Pallars Jussà'},
    {code: 'Pallars Sobirà', name: 'Pallars Sobirà'},
    {code: 'Pla Estany', name: 'Pla Estany'},
    {code: 'Pla Urgell', name: 'Pla Urgell'},
    {code: 'Priorat', name: 'Priorat'},
    {code: 'Resta Estat Espanyol', name: 'Resta Estat Espanyol'},
    {code: 'Resta Estat Francès', name: 'Resta Estat Francès'},
    {code: 'Resta Món', name: 'Resta Món'},
    {code: 'Ribera Ebre', name: 'Ribera Ebre'},
    {code: 'Ripollès', name: 'Ripollès'},
    {code: 'Roselló', name: 'Roselló'},
    {code: 'Segarra', name: 'Segarra'},
    {code: 'Segrià', name: 'Segrià'},
    {code: 'Selva', name: 'Selva'},
    {code: 'Solsonès', name: 'Solsonès'},
    {code: 'Tarragonès', name: 'Tarragonès'},
    {code: 'Terra Alta', name: 'Terra Alta'},
    {code: 'Urgell', name: 'Urgell'},
    {code: 'Val Aran', name: 'Val Aran'},
    {code: 'Vallès Occidental', name: 'Vallès Occidental'},
    {code: 'Vallès Oriental', name: 'Vallès Oriental'},
    {code: 'Vallespir', name: 'Vallespir'},
];